project_id = "gzpypxgdkxdynovploxn"

[functions.stripe-webhook]
verify_jwt = false

[functions.setup-stripe-products]
verify_jwt = false

[functions.detect-winners]
verify_jwt = false

[functions.archive-year-products]
verify_jwt = false

[functions.subscribe-to-newsletter]
verify_jwt = false

[functions.sync-users-to-beehiiv]
verify_jwt = true

[functions.stripe-connect-oauth]
verify_jwt = false
