project_id = "gzpypxgdkxdynovploxn"

[functions.stripe-webhook]
verify_jwt = false

[functions.setup-stripe-products]
verify_jwt = false

[functions.detect-winners]
verify_jwt = false

[functions.archive-year-products]
verify_jwt = false
